config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :guests
  resources :beds

  root "guests#new"

  post "reservations/:id/checkin", to: "reservations#assign_beds", as: :reservation_check_in
  post "reservations/:id/checkout", to: "reservations#unassign_beds", as: :reservation_check_out
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bed.rb
class Bed < ApplicationRecord
  belongs_to :reservation, optional: true

  def is_available
    where("available is TRUE")
  end

  def self.count_available
    where("available is TRUE").count
  end
end

app/models/guest.rb
class Guest < ApplicationRecord
  has_many :reservations

  validates_presence_of :name

  accepts_nested_attributes_for :reservations
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :guest
  has_many :beds

  validates_presence_of :checkin

  def beds_assigned
    beds.ids
  end

  def self.checkin_today
    where(:checkin => Time.now)
  end

  def self.checkout_today
    where(:checkout => Time.now)
  end

  def self.upcoming
    where("checkin > ?", Date.today)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/beds_controller.rb
class BedsController < ApplicationController
  before_action :set_bed, only: [:show, :edit, :update, :destroy]

  def index
    @beds = Bed.all
  end

  def show
  end

  def new
    @bed = Bed.new
  end

  def edit
  end

  def create
    @bed = Bed.new(bed_params)

    respond_to do |format|
      if @bed.save
        format.html { redirect_to @bed, notice: 'Bed was successfully created.' }
        format.json { render :show, status: :created, location: @bed }
      else
        format.html { render :new }
        format.json { render json: @bed.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @bed.update(bed_params)
        format.html { redirect_to @bed, notice: 'Bed was successfully updated.' }
        format.json { render :show, status: :ok, location: @bed }
      else
        format.html { render :edit }
        format.json { render json: @bed.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @bed.destroy
    respond_to do |format|
      format.html { redirect_to beds_url, notice: 'Bed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_bed
      @bed = Bed.find(params[:id])
    end

    def bed_params
      params.require(:bed).permit(:available, :reservation_id)
    end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_action :set_guest, only: [:show, :edit, :update, :destroy]

  def index
    @guests = Guest.all
  end

  def show
  end

  def new
    @guest = Guest.new
    @guest.reservations.build
  end

  def edit
  end

  def create
    @guest = Guest.new(guest_params)

    respond_to do |format|
      if @guest.save
        format.html { redirect_to @guest, notice: 'Guest was successfully created.' }
        format.json { render :show, status: :created, location: @guest }
      else
        format.html { render :new }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @guest.update(guest_params)
        format.html { redirect_to @guest, notice: 'Guest was successfully updated.' }
        format.json { render :show, status: :ok, location: @guest }
      else
        format.html { render :edit }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @guest.destroy
    respond_to do |format|
      format.html { redirect_to guests_url, notice: 'Guest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_guest
      @guest = Guest.find(params[:id])
    end

    def guest_params
      params.require(:guest).permit(:name, reservations_attributes: [:id, :checkin, :checkout, :number_of_beds])
    end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy, :assign_beds, :unassign_beds]

  def index
    @reservations = Reservation.all
  end

  def show
  end

  def new
    @reservation = Reservation.new
  end

  def edit
  end

  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  def assign_beds
    @beds = Bed.where("available is true")
               .first(@reservation.number_of_beds)
               .each do |bed|
      unless (Bed.where(:reservation_id => @reservation.id).count == @reservation.number_of_beds)
        bed.update_attributes(available: false, reservation_id: @reservation.id)
      end
    end
    redirect_to reservations_url
  end

  def unassign_beds
    @beds = Bed.where(:reservation_id => @reservation.id).each do |bed|
      bed.update_attributes(available: true, reservation_id: nil)
    end
    redirect_to reservations_url
  end

  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    def reservation_params
      params.require(:reservation).permit(:checkin, :checkout, :guest_id, :number_of_beds)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/beds/_form.haml
= form_with(model: bed, local: true) do |form|
  - if bed.errors.any?
    #error_explanation
      %h2
        = pluralize(bed.errors.count, "error")
        prohibited this bed from being saved:
      %ul
        - bed.errors.full_messages.each do |message|
          %li= message

  .field
    = form.label :available
    = form.text_field :available, id: :bed_available

  .field
    = form.label :reservation_id
    = form.text_field :reservation_id, id: :reservation_id

  .actions
    = form.submit "Submit"

app/views/beds/edit.haml
%h1 Editing Bed
= render 'form', bed: @bed
= link_to 'Show', @bed
|
= link_to 'Back', beds_path

app/views/beds/index.haml
.beds-index
  .top-nav-container
    %p#notice= notice
    .upper-left-nav
      %h1 Beds Available
      %h4 Available Beds: #{@beds.count_available} out of #{@beds.all.count}
    .upper-right-nav
      = link_to "New Bed", new_bed_path
      = link_to "View all Reservations", reservations_url
  .beds-container
    - @beds.each do |bed|
      %table{:class => "#{bed.available ? 'available' : 'reserved'}"}
        %tr
          %td
            %p= "Bed # #{bed.id}"
            %p= "Reservation ID: #{bed.reservation ? (link_to bed.reservation.id, reservation_url(bed.reservation.id)) : "n/a"}"
            %p= bed.reservation ? bed.reservation.checkin : nil
            %p= bed.reservation ? bed.reservation.checkout : nil
            %p= bed.available ? "available" : "reserved"
            %p= link_to 'Edit', edit_bed_path(bed)

app/views/beds/new.haml
%h1 Add a Bed
= render 'form', bed: @bed
= link_to 'Show', @bed
|
= link_to 'Back', beds_path

app/views/beds/show.haml
%p#notice= notice
%p
  %strong Reservation #:
  = @bed.reservation ? @bed.reservation.id : "n/a"
%p
  %strong Checkin:
  = @bed.reservation ? @bed.reservation.checkin : "n/a"
%p
  %strong Checkout:
  = @bed.reservation ? @bed.reservation.checkout : "n/a"
%p
  %strong Available:
  = @bed.available

= link_to 'Edit', edit_bed_path(@bed)
|
= link_to 'Back', beds_path

app/views/guests/_form.haml
.form-container
  = form_with(model: guest, local: true) do |form|
    - if guest.errors.any?
      #error_explanation
        %h2
          = pluralize(guest.errors.count, "error")
          prohibited this guest from being saved:
        %ul
          - guest.errors.full_messages.each do |message|
            %li= message
    .field
      = form.text_field :name, id: :guest_name, placeholder: "Full Name"

    = form.fields_for :reservations do |r|
      .field
        = r.text_field :checkin, id: :reservation_checkin, placeholder: "Checkin"
        = r.text_field :checkout, id: :reservation_checkout, placeholder: "Checkout"
        = r.text_field :number_of_beds, id: :number_of_beds, placeholder: "Number of Guests"

    .actions
      = form.submit "Submit"

  :javascript
    var checkin_datepicker = new Pikaday({
      field: document.getElementById('reservation_checkin')
    });
    var checkout_datepicker = new Pikaday({
      field: document.getElementById('reservation_checkout')
    });

app/views/guests/edit.html.erb
<h1>Editing Guest</h1>

<%= render 'form', guest: @guest %>

<%= link_to 'Show', @guest %> |
<%= link_to 'Back', guests_path %>

app/views/guests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Guests</h1>
<%= link_to 'Beds', beds_url %>
<%= link_to 'Reservations', reservations_url %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guests.each do |guest| %>
      <tr>
        <td><%= guest.name %></td>
        <td><%= link_to 'Show', guest %></td>
        <td><%= link_to 'Edit', edit_guest_path(guest) %></td>
        <td><%= link_to 'Destroy', guest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guest', new_guest_path %>

app/views/guests/new.haml
.guest-form
  %h1 Make a Reservation
  = render 'form', guest: @guest
  = link_to 'Back', reservations_path

app/views/guests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @guest.name %>
</p>
<p>
  <% @guest.reservations.each do |reservation| %>
    <strong>Checkin:</strong>
    <%= reservation.checkin %>
    <strong>Checkout:</strong>
    <%= reservation.checkout %>
  <% end %>
</p>

<%= link_to 'Edit', edit_guest_path(@guest) %> |
<%= link_to 'Back', guests_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReservationsSystem</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reservations/_form.haml
= form_with(model: reservation, local: true) do |form|
  - if reservation.errors.any?
    #error_explanation
      %h2
        = pluralize(reservation.errors.count, "error")
        prohibited this reservation from being saved:
      %ul
        - reservation.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :checkin
    = form.text_field :checkin, id: :reservation_checkin
  .field
    = form.label :checkout
    = form.text_field :checkout, id: :reservation_checkout
  .field
    = form.label :guest_id
    = form.text_field :guest_id, id: :reservation_guest_id
  .field
    = form.label :number_of_beds
    = form.text_field :number_of_beds, id: :reservation_number_of_beds
  .actions
    = form.submit

:javascript
  var checkin_datepicker = new Pikaday({ field: document.getElementById('reservation_checkin') });
  var checkout_datepicker = new Pikaday({ field: document.getElementById('reservation_checkout') });

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.haml
.reservations-index
  .reservations-container
    %p#notice= notice
    .top-nav-container
      .upper-left-nav
        %h1 Reservations for #{Time.now.strftime("%B %-d, %Y")}
      .upper-right-nav
        = link_to 'New Reservation', new_guest_path
        = link_to 'See Available Beds', beds_path
    .reservations-columns-container
      .reservations-column
        %h2 Arriving Today
        - @reservations.checkin_today.each do |reservation|
          .reservations-item
            .reservation-details
              %p Reservation ID: #{reservation.id}
              %p
                Guest Name:
                %strong #{reservation.guest.name}
              %p Checkout Date: #{reservation.checkout}
              %p Number of Guests: #{reservation.number_of_beds}
              %p Beds Assigned: #{reservation.beds_assigned}
            .reservation-action-item
              %p= link_to 'Show', reservation
              %p= link_to 'Edit', edit_reservation_path(reservation)
              %p= link_to 'Check In', reservation_check_in_path(reservation), method: :assign_beds
              %p= link_to 'Cancel Reservation', reservation, method: :delete, data: { confirm: 'Are you sure?' }

      .reservations-column
        %h2 Departing Today
        - @reservations.checkout_today.each do |reservation|
          .reservations-item
            .reservation-details
              %p Reservation ID: #{reservation.id}
              %p
                Guest Name:
                %strong #{reservation.guest.name}
              %p Checkout Date: #{reservation.checkout}
              %p Number of Guests: #{reservation.number_of_beds}
              %p Beds Assigned: #{reservation.beds_assigned}
            .reservation-action-item
              %p= link_to 'Show', reservation
              %p= link_to 'Edit', edit_reservation_path(reservation)
              %p= link_to 'Check Out', reservation_check_out_path(reservation), method: :unassign_beds
              %p= link_to 'Cancel Reservation', reservation, method: :delete, data: { confirm: 'Are you sure?' }

      .reservations-column
        %h2 Upcoming Reservations
        - @reservations.upcoming.each do |reservation|
          .reservations-item
            .reservation-details
              %p Reservation ID: #{reservation.id}
              %p
                Guest Name:
                %strong #{reservation.guest.name}
              %p Checkin Date: #{reservation.checkin}
              %p Checkout Date: #{reservation.checkout}
              %p Number of Guests: #{reservation.number_of_beds}
            .reservation-action-item
              %p= link_to 'Show', reservation
              %p= link_to 'Edit', edit_reservation_path(reservation)
              %p= link_to 'Cancel Reservation', reservation, method: :delete, data: { confirm: 'Are you sure?' }

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Checkin:</strong>
  <%= @reservation.checkin %>
</p>

<p>
  <strong>Checkout:</strong>
  <%= @reservation.checkout %>
</p>

<p>
  <strong>Guest:</strong>
  <%= link_to @reservation.guest.name, guest_url %>
</p>

<p>
  <strong>Number of Beds:</strong>
  <%= @reservation.number_of_beds %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>